name: Bug Report
description: File a bug report here
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: 小
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 楔 小携
      description: Steps to reproduce the behavior.
      placeholder: Please write the steps in a list form
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: 蝎 校鞋孝孝
    validations:
      required: true
  - type: textarea
    id: actual-result
    attributes:
      label: 肖孝效小 校鞋孝孝
    validations:
      required: true      
  - type: textarea
    id: environment
    attributes:
      label: 校
    validations:
      required: true
