name: 游냍Bug Report
description: File a bug report here
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-priority
    attributes:
      label: 먫떓뤯먫떓뭻돯
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: 뤯햊햐햃햏햊햇
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 햗햃햅햊 뉋뤯뫓먫뤯떓뉋돯덇돯뢇떓
      description: Steps to reproduce the behavior.
      placeholder: Please write the steps in a list form
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: 뤯뒗떓덇냻돯럟햋 먫돯햒햍햛햑햃햑
    validations:
      required: true
  - type: textarea
    id: actual-result
    attributes:
      label: 햓햃햌햑햊햖햇햐햌햊햋 먫돯햒햍햛햑햃햑
    validations:
      required: true      
  - type: textarea
    id: environment
    attributes:
      label: 뤯뛣먫했햇햏햊햇
    validations:
      required: true
